### ISSUE TITLE
Import LTR judgement list format

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#162]
**Is your feature request related to a problem? Please describe.**
Here is the current manual workaround process to import an LTR judgement list:
1. Change \t -> , and remove extra spaces and # symbol
2. Import the csv into a google spreadsheets
3. Rearrange columns from "rating,docid,query" into "query,docid,rating" format
4. Import the update csv file into Quepid

**Describe the solution you'd like**
Support LTR format directly:
    
    rating\tquerid\tdocid\tquery
    2\tqid:1234567890\t# docid1\tguidance

**Value to the users**
1. Value to domain experts
The workflow with the ability to import LTR (effectively RankLib) judgement list directly into Quepid enables relevance engineers to upload synthetically rated query/document pairs into Quepid to share with domain experts. This allows to proof-read the judgement lists, as well as use all Quepid goodies, like comparing rankers / query parameters with respect to a scorer.

2. Value to relevance engineers: pin-point particular queries in a judgement list that have been positively / negatively impacted by an LTR model.

**Comment by nathancday** [comment]
We definitely want the export/import process from LTR to be a seamless as possible, it sounds like we need to adjust our import code .

I will look at this and try to make the Quepid-LTR format match exactly with the og LTR format.

**Comment by DmitryKey** [comment]
thanks @nathancday Indeed this will streamline the import / export process specifically for LTR developers.

**Comment by epugh** [comment]
Is the LTR format a widely used, well understood format?  Any chance of changing it to the one that Quepid already used?   I only ask because the Quaerite folks were able to change their format to match Quepid's ;-)   Otherwise, I bet we could autodetect the LTR format and change it up...   Just more complex ;-)

**Comment by epugh** [comment]
@DmitryKey @nathancday Is this still a valid issue?  In re-reading this, I think you are asking to IMPORT into Quepid, and we currently have an EXPORT that looks like `rating qid:queryid # docid` eg `1 qid:23 # 193`.   You are saying we don't have a equivalent IMPORT yet....?

**Comment by DmitryKey** [comment]
@epugh yep, this is import and yes, Quepid does not support it, only export. If IMPORT would support `rating qid:queryid # docid` format -- that would be awesome, because I can convert the CSV in question into this format.

Of course, if plain CSV is easier -- as stated in the issue -- I'm totally up for it too! Less work :)

**Comment by epugh** [comment]
I hate constantly reformatting CSV's...   For some reason I read it back in June as EXPORT ;-)    Doh.   I think I can add it.

**Comment by DmitryKey** [comment]
if only we could spec JSON format with defined schemas -- and convince LTR community to use it.. :) Dreams!

**Comment by o19s-admin** [comment]
+1 to those dreams.    This is where having someone like yourself get more involved in these communities would be powerful.  I suspect you would get more traction in those communities than I would, but if you can get a format committed to any of those, I’ll be very happy to do an update on Quepid end of things ;-)On Aug 28, 2020, at 6:40 AM, Dmitry Kan <notifications@github.com> wrote:if only we could spec JSON format with defined schemas -- and convince LTR community to use it.. :) Dreams!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

_______________________Eric Pugh | Founder & CEO | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com | My Free/Busy  Co-Author: Apache Solr Enterprise Search Server, 3rd Ed	This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by epugh** [comment]
Today we export like this:

```
1    qid:33 #    12180; "star wars"
1    qid:33 #    13532; "star wars"
1    qid:33 #    1895; "star wars"
0    qid:33 #    85; "star wars"
1    qid:33 #    1894; "star wars"
1    qid:33 #    1891; "star wars"
```

What are your thoughts @DmitryKey on the `qid`?   

1) Would that update a existing query (with that id)?  Or do we ignore that value?    Maybe if you mark the clear Queries option, we ignore the `qid`, cause you have deleted it, otherwise we look up the query and doc id combination, and then update rating. 

2) Likewise with the query text after teh `#`, should we just ignore that since it's meant for documentation?

**Comment by epugh** [comment]
@DmitryKey was hoping for some feedback, as I've just finished the import function.   We ignore the qid:XX parameter, but do use the query text, so more like a regualrd csv import.   If you think the qid is the key bit,t hen I can look up the query and the doc pair based on that, hwoever, it will fail if you don't have a query already loaded iwth that qid.

**Comment by epugh** [comment]
Okay, rolling !
