### ISSUE TITLE
Scorer Options page is not very intuitive

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#422]
**Is your feature request related to a problem? Please describe.**
When I land to the Scorer Options page, my usual goal is to create / modify a custom scorer. I very rarely choose a default scorer, maybe once for the entire Quepid deployment, because things like this tend to be much more stable: i.e. which metric we are optimizing as a team.

The visual confusion I get is with this upper part of the page:
![Screenshot 2021-09-30 at 9 25 18](https://user-images.githubusercontent.com/123553/135398773-278fe985-2bb9-45b2-8363-ca9358e8ff73.png)

My eyes are scanning left to right, top to bottom, but I can't find, what I'm looking for:
![Screenshot 2021-09-30 at 9 26 18](https://user-images.githubusercontent.com/123553/135398884-8142d4dc-e837-41ae-b571-2d87cad81b6b.png)

because it is way too small, it is in the middle section of the page (a bit to the left from the middle on a larger screen), surrounded by buttons and text inputs.

**Describe the solution you'd like**
It would be cool to rework this part of the page into a more robust set of options, something like tabs:

1. Create / modify a scorer
2. Change defaults -- may be a scorer could be a property of a case and live in the Settings page?
3. Filter scorers could be right above the list of scorers -- the list looks great from the UX standpoint btw!

**Comment by peterdm** [comment]
(Here's an alternate take on the visual confusion Dmitry)

**Is your feature request related to a problem? Please describe:**  This page imposes a filtered view on scorers which promotes communal scorers while hiding custom scorers.  (And it is not necessarily clear to users that their view is filtered).

**Describe the solution you'd like:**  "Scorer Buffet" (Don't filter):

1.  Remove the filter widget and don't filter the table.  
2. Add a `Visibililty` column to the table with current options ("Public", "Creator Teammates" – is this an accurate statement for Custom scorers at the moment?).
3. Rank (dogfood - oh yeah!!) the list so that the scorers used more heavily/recently for my cases bubble up.
