### ISSUE TITLE
Chrome 94 blocks CORS and breaks image thumbnails

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#426]
**Describe the bug**
After upgrading to recent Chrome 94, the images in Quepid don't load properly:

![image](https://user-images.githubusercontent.com/123553/136216903-9c096cc4-3e73-40c3-822a-65e7bc9ec467.png)

Also userpic from gravatar does not load:
![image](https://user-images.githubusercontent.com/123553/136217441-0b2ffb29-ae66-4564-a0c6-fdfa9e42fad6.png)

**To Reproduce**
1. Install Chrome 94
2. Login to Quepid
3. Observe some broken images

**Expected behavior**
Images should load as before

**Context**
Quepid is installed in non-http way.
There are a few solutions outlined here: https://developer.chrome.com/blog/private-network-access-update/#both-ends-https

**Comment by epugh** [comment]
eric  3 minutes ago
we could add to quepid some sort of “grabber”




eric  2 minutes ago
if your image is https://gravatar.com/dmitry

eric  2 minutes ago
and you do….

eric  2 minutes ago
thumb:image_url

eric  2 minutes ago
if we are on http and the image_url starts with https….

eric  2 minutes ago
then we do

eric  1 minute ago
<img src="http://app.quepid.com/api/grabber?url=https://gravatar.com/dmitry/">

eric  < 1 minute ago
and /api/grabber takes the URL, and goes and gets it…..

eric  < 1 minute ago
i don’t love putting Quepid in the middle of the query path…..

eric  < 1 minute ago
since it’s not opitmized for serving up thousands of requests from the server, but this COULD work…
