### ISSUE TITLE
Average Query Execution Time

### ISSUE THREAD

**Issue by danielibars** [o19s/quepid#439]
**Is your feature request related to a problem? Please describe.**
During query development it is important to keep track how much time it takes to run the resulting query.

**Describe the solution you'd like**
It could be great to have a query time metric somewhere in the UI that let you know how much time your query is taking to run

**Describe alternatives you've considered**
For Elasticsearch every search json response comes with a field called **"took"** which express the time in milliseconds it took to run that particular query. However this value is just the time Elasticsearch spent on executing the query once it processed it. 
The caveat for this metric is that maybe Solr has a different approach, making it difficult to homologate for both search engines.

Another approach should be measuring the time it took to run in the browser, this way no matter if it is either elasticsearch or Solr, the measuring method is potentially the same.

**Additional context**
Here in my new job at Rappi, are having serious issues with query performance, so for us and actually any query developer should be concerning, as a poorly developed query can cause unnecessary performance issues that could lead to the need of adding more nodes, causing more spend that it is actually necessary.

Quepid can help figuring query time/performance issues out if you can include a time metric in the UI

Thanks

Danny

**Comment by epugh** [comment]
At first this didn't seem like something that Quepid would be set up to help with....   That you would want something like Gatling etc that generates LOTS of load, and understands how to warm up your target server, then do lots of queries, and then cool down, etc.   

However, one of the goals of Quepid is just to surface better the information that already exists in the search engine, whether the *took* in ES or the *QTime* in Solr....  

I think if your goal is to get a sense of how changes to the query impact query performance, that would be just fine!   However I don't think Quepid will evolve into a load tester.

Since how the browser sends queries to the search engine is not very predictable/controlled, due to it's being a in browser app that queues them up and then runs them, I think the best we could do is surface the time the engine took to run query, not the overall clock time as experienced by the user....   

We could track this information, maybe add some sort of stopwatch icon or have a detail view for this.  You could use the snapshot feature to compare over time.  We could even add up the times for the entire Case, and maybe have an average? 

This ticket honestly would benefit by having some UI mockups and some more design thinking...    Maybe a topic for our next Qommunity Qoding?

**Comment by peterdm** [comment]
No question this could be useful interactively while experimenting with ad-hoc query changes in Quepid.  I'd be concerned about this becoming a reporting feature though, as some might forgo actual load testing and report these numbers out (to the detriment of their search uptime).  

Many people run Quepid against non-prod engines and/or static collections and this would not be a useful metric in those cases.  Also Quepid, having a prescribed query set, would have a tendency to warm caches in favor of the case just run (not a realistic simulation of real traffic).

**Comment by danielibars** [comment]
I'm totally with Eric, the purpose of this feature request is to have a sense of how different query clauses are impacting the overall performance of your in progress query.
By no means this should be considered a performance evaluation feature.

**Comment by epugh** [comment]
Met with @danielibars and @DmitryKey and we brainstormed on Miro what we could do, both immediately and longer term.   Notes/ideas/screenshots at https://miro.com/app/board/o9J_lj2ClFc=/?moveToWidget=3074457367541579081&cot=14

**Comment by epugh** [comment]
![image](https://user-images.githubusercontent.com/22395/141519817-09e45d42-acb6-41b9-a882-87e64e3a4c3d.png)
