### ISSUE TITLE
Request delay for cases to avoid "429 - Too many requests"?

### ISSUE THREAD

**Issue by KennyLindahl** [o19s/quepid#441]
Sorry if this is not the right forum, but i get "429 - Too many requests" from Elasticsearch since all `271` search word requests are being sent at once in my Case.
Is there any way to have a delay or make the requests wait for each other to avoid this issue?

I have tried to look in the Quepid UI and in the documentation & repo but could not find anything that could control the requests frequency.
Thanks in advance.

**Comment by epugh** [comment]
I've been struggling on this, as someone said they saw the same thing, but with Solr...   However, my understanding is that we limit the number of concurrent requesrts...    That they are a bunch of Promises, and then we get the results back as they run.   I was under the impression that browers LIMIT how many requests are sent at once...

**Comment by epugh** [comment]
I put together this document that might be of interest:

https://docs.google.com/document/d/15x259J-gvUn1CBpj4dmfoTO1czaEaBIlWEt_BYFXs0w/edit?usp=sharing

Also @KennyLindahl we might need a pair programming session to really try and understand how this happening...   Because theorectically it shouldn't!!!!!!    Want to look at getting together next week Friday?   Say Feb 25th and looking in more depth?

**Comment by epugh** [comment]
Would this Friday 2/25 at 9 AM EST/ 15:00 your time work?   Please send intive to that email!

**Comment by KennyLindahl** [comment]
@epugh Yes, i will send you an invite 😄
