### ISSUE TITLE
Extra search query parameters

### ISSUE THREAD

**Issue by llermaly** [o19s/quepid#446]
**Is your feature request related to a problem? Please describe.**
I have a query with some parameters generated outside ES that I use as filters depending on the search query.

**Describe the solution you'd like**
Ability to add extra columns to the CSV, that way I can use these fields in the query.

Example:

query,docid,rank,param1,param2,param3
myquery,id1,1,someparam,someotherparam,['array','of','params']

Allowing arrays would be even better.

Then in the query do something like :

```
"match":{"field": "#query_string#"}
"filter": [{"term":{"field2": "#param_1#"}, {"terms": "#param3#".}]

```
**Describe alternatives you've considered**
The only thing I can think of is to create 1 case per search query and hardcode the values in the query but we have tons of queries so will take a long time.

**Additional context**
We really want to use Quepid but we have this 2 situations, one are the query dependant dynamic parameters, and the other one is the search terms are spread across the query, so we need a way to split the search term into word and use this words in different statements.

Thanks

**Comment by epugh** [comment]
There is some plumbing for this, you can define per query a hash that you reference in a scorer as `qOption(key)`...   So I think the lift to add this to the query generation wouldn't be terrible.    Having said that, what this feels like is that we need a way of importing queries for a case where we basically just use the native ActiveRecord object model to import a big complex JSON data structure, instead of constantly adding more complex data structures into what is essentially a single row per line format that CSV is.
