### ISSUE TITLE
Picking ES, then changing http to https in wizard loses es selection

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wrigleyDan** [comment]
This issue also appears when changing from https to http in the wizard:
1. You are on a secure Quepid installation, e.g. https://app.quepid.com/
2. Create a new case, select Elasticsearch as the search engine and point it towards a not secure Elasticsearch installation:
![image](https://user-images.githubusercontent.com/54574577/150534087-bb26c7e5-efc4-4b7c-adfa-a7cf8efb374e.png)
1. Hit the "Reload Quepid" button.
2. Move through the rest of the wizard.
3. In the Query Sandbox you can see the default Solr query instead of the default Elasticsearch query:
![image](https://user-images.githubusercontent.com/54574577/150534456-e4020c00-e5c2-4c2e-a64b-0d2b756f3dd1.png)

As a result, Quepid uses the default Solr query to query Elasticsearch which obviously cannot yield results. So in the described scenario not all defaults are reset when Quepid is "reloaded" when changing from http to https (or the other way round).

**Comment by epugh** [comment]
This was supposed to be fixed by https://github.com/o19s/quepid/pull/459 but clearly isn't, I just tested it again and can see the problem.  I think we need to dig a bit more into where we decide to set defaults...
