### ISSUE TITLE
Showing if a query has notes

### ISSUE THREAD

**Issue by anegyesi** [o19s/quepid#477]
Similar to the frog for queries with missing valuations, it would be great to have some icon to show queries with notes.

**Comment by epugh** [comment]
Thoughts on this suggestion?

**Comment by epugh** [comment]
I am also thinking, maybe instead of cluttering up the core JS app with more features, what if I add a "Case Query Set Analytics" screen?   A seperate screen that has lots of filters and data points?   Queries with Notes?  Queries with Info Needs?   What are all the things you'd like to see?  it can be more dashboard oriented...
