### ISSUE TITLE
"nDCG@10" scorer always returns 100

### ISSUE THREAD

**Issue by TheSench** [o19s/quepid#77]
**Describe the bug**
`nDCG@10` scorer is returning a score of 100, regardless of how I score the documents the query is returning.

**To Reproduce**
1. Go to 'Movies Search' case
1. Ensure Scorer is set to `nDCG@10`
1. Add a query for 'test'
1. Score all documents as a 1 (Poor)
1. Note that overall score remains at 100

**Expected behavior**
Marking all results as "Poor" should cause the overall score for the query to be lowered.

**Screenshots**
![image](https://user-images.githubusercontent.com/9260413/74480426-e3a04a00-4e7e-11ea-93b7-3d0e82b8a4b2.png)

**Additional context**

**Comment by TheSench** [comment]
This can be reproduced, even when the total result set has less than 10 records in it.

**Comment by epugh** [comment]
I'm chatting with @worleydl on this...    Going to try and capture what I'm learning in this ticket.

**Comment by epugh** [comment]
If you score everything as 1 OR you score everything as 2 OR your score everything as a 3, OR your score everthing as a 4, the way NDCG works, you will always get 100 as the score, because if all the rated docs have the same value, then they are ALL in the ideal order.   

However, if you don't score all 10 (which is what we are looking at), then you have some blanks, which means that the score will drop.  So if you give the first ranking a 1, and the rest are empty, your score drops.  Until you give ALL 10, and then if they are all in the same number, you get 100.  

So, if you do 1,4,1,1,1,1,1,1,1,1 you get 72.   But, if you change it to 4,1,1,1,1,1,1,1,1,1, boom, you are back to 100.

This "all 1's is the same as all 2's" is a weakness of the current implementation of NDCG, and we don't know if there is a better version of it.  Conversation for Haystack conference ;-).

So now, let's look at NDCG@10 for less then 10 results.

If you only have 1 result, then it doesn't matter what you set the rating to, you'll only have that one value, ergo you always get 100 as the score.  See, the limitation above.

Now, let's talk about the situation where we have a single result, with say a rating of 1.  We start out with 100 score, which makes sense.  However, using Explain Other we rate another document as a 4.   My thinking is that this missing document should now be included, and since the 4 is lower int he list than the 1 (as in, not even showing up), then the rating would drop from 100, just like if you had a result like 1, 4.

**Comment by epugh** [comment]
A thought then, is even if NDCG is right that all 1's or all 2's is 100, maybe we should alert the user?   "We know you have 100, but you are only showing low ranked docs".  Unless it's all 4's!!!

**Comment by epugh** [comment]
Okay, so the all 1's @TheSench is "How NDCG works".   However, this doesn't answer the question of what to do if you have 1 doc rated, but you have marked other (not included in search results) docs rated.

**Comment by binarymax** [comment]
Hi @TheSench this is a known (and strange) behavior of nDCG, and is explained in more detail in this blog post I wrote: https://opensourceconnections.com/blog/2019/12/09/demystifying-ndcg-and-err/

**Comment by TheSench** [comment]
Thanks for the information.  I understand now that, at a high level, nDCG is essentially checking that all documents are returned in the correct order (or at least the top 10).  I do think missing documents should be taken into account in that scoring, as "returning a 1, but completely excluding a 4" could be considered a case of "incorrect order", but that's now covered in #78 .

**Comment by epugh** [comment]
I am going to reopen this, as I think that the knowledge captured in this ticket needs to be in the Wiki for the next person's education, so I'd like to keep this issue till we get that done.

**Comment by epugh** [comment]
@TheSench can you read over https://github.com/o19s/quepid/wiki/How-Scoring-Works-in-Quepid and let me know what you think?  Would this doc have helped you?  Feel free to make any edits for clarity.   I still sort of want to add something to quepid to warn you "Every doc is a 1, yet you have 100"....   Haven't quite figured out how that would work though.  Maybe there is another scorer that would deal with that?

**Comment by TheSench** [comment]
The way I've been looking at it, the local nDCG scorer essentially boils down to how well the results are sorted based on their scores.

**Comment by TheSench** [comment]
I do think the wiki page sums up what's going on, although it feels like the important pieces are buried at the end of their sections.

**Comment by epugh** [comment]
Thanks, I may take another stab at reorginziing.  I don't love how NDCG works, and there was some discussion about it, but I guess it "works as ndcg local" is designed.  Going to close this for now.
