### ISSUE TITLE
Notes for a query disappears after collapse+expand query

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#87]
**Describe the bug**
Notes on a query are lost when you collapse then expand the query. But after a full page refresh they come back again.

**To Reproduce**
1. Add a note to a query
2. Collapse by clicking on the query line
3. Expand again and toggle Notes box
4. The note you wrote is gone
5. Refresh your browser page
6. Open up the query and the Notes panel again - the note is there

**Comment by epugh** [comment]
Thanks @janhoy for reporting, and @worleydl for the fix.   I did want to mention that there *may* be an issue where as you type a note, we send updates to the database, and if they get out of order due to slow API, you may see some weridness.   I can't confirm this problem, but if you see something...
